// Generated by the Tensor Algebra Compiler (tensor-compiler.org)
// taco "A(i,j) = B(i,j) * C(i,j)" -f=B:ds -f=C:sq

// Modified to remove references to `taco_tensor_t` by passing everything as func args

void compute(int max_j,
             double* restrict A_vals,

             int* restrict B_pos,
             int* restrict B_crd,
             double* restrict B_vals,

             int* restrict C1_pos,
             int* restrict C1_crd,
             int* restrict C2_crd,
             double* restrict C_vals) {

  for (int iC = C1_pos[0]; iC < C1_pos[1]; iC++) {
    int i = C1_crd[iC];
    int jB = B_pos[i];
    int pB2_end = B_pos[(i + 1)];
    int jC = iC;
    int pC2_end = iC + 1;

    while (jB < pB2_end && jC < pC2_end) {
      int jB0 = B_crd[jB];
      int jC0 = C2_crd[jC];
      int j = jB0 < jC0 ? jB0 : jC0;
      if (jB0 == j && jC0 == j) {
        int jA = i * max_j + j;
        A_vals[jA] = B_vals[jB] * C_vals[jC];
      }
      jB += (int)(jB0 == j);
      jC += (int)(jC0 == j);
    }
  }

}
