#include <stdint.h>

// Generated by the Tensor Algebra Compiler (tensor-compiler.org)
// taco "A(i,j)=B(i,j)*C(i,k)*D(k,j)" -f=A:ss:0,1 -f=B:ss:0,1 -f=C:dd:0,1 -f=D:dd:0,1

void compute(double* restrict A_vals,

            // B is in Double CSR
            int* restrict B1_pos,
            int* restrict B1_crd,
            int* restrict B2_pos,
            int* restrict B2_crd,
            double* restrict B_vals,

            int C2_dimension,
            double* restrict C_vals,

            int D1_dimension,
            int D2_dimension,
            double* restrict D_vals) {

  int32_t jA = 0;

  for (int32_t iB = B1_pos[0]; iB < B1_pos[1]; iB++) {
    int32_t i = B1_crd[iB];
    for (int32_t k = 0; k < D1_dimension; k++) {
      int32_t kC = i * C2_dimension + k;
      for (int32_t jB = B2_pos[iB]; jB < B2_pos[(iB + 1)]; jB++) {
        int32_t j = B2_crd[jB];
        A_vals[jA] = 0.0;
        int32_t jD = k * D2_dimension + j;
        A_vals[jA] = A_vals[jA] + (B_vals[jB] * C_vals[kC]) * D_vals[jD];
        jA++;
      }
    }
  }

}
