#include <stdint.h>

// Generated by the Tensor Algebra Compiler (tensor-compiler.org)
// taco "A(i,k)=B(i,j)*C(j,k)" -f=A:dd:0,1 -f=B:ds:0,1 -f=C:dd:0,1

// Modified to remove references to `taco_tensor_t` by passing everything as func args
// Added comments

int compute(int A2_dimension,
            int B1_dimension,
            int C2_dimension,
            double* restrict A_vals,
            double* restrict C_vals,

            // B is in CSR
            int* restrict B2_pos,
            int* restrict B2_crd,
            double* restrict B_vals) {

    for (int32_t i = 0; i < B1_dimension; i++) {
        for (int32_t jB = B2_pos[i]; jB < B2_pos[(i + 1)]; jB++) {
            int32_t j = B2_crd[jB];
            for (int32_t k = 0; k < C2_dimension; k++) {
                int32_t kA = i * A2_dimension + k;
                int32_t kC = j * C2_dimension + k;
                A_vals[kA] = A_vals[kA] + B_vals[jB] * C_vals[kC];
            }
        }
  }

  return 0;
}
