// Generated by the Tensor Algebra Compiler (tensor-compiler.org)
// taco "a(i) = B(i,j) * c(j)" -f=B:ds

// Modified to remove references to `taco_tensor_t` by passing everything as func args
// Removed 0 initialization of a

int compute(double* restrict a_vals,
	    int num_of_rows,
	    int* restrict pos,
	    int* restrict crd,
	    double* restrict B_vals,
	    double* restrict c_vals) {

  for (int i = 0; i < num_of_rows; i++) {
    double res = 0.0;
    for (int jj = pos[i]; jj < pos[i + 1]; jj++) {
      res += B_vals[jj] * c_vals[crd[jj]];
    }
    a_vals[i] = res;
  }
  return 0;
}
