// Generated by the Tensor Algebra Compiler (tensor-compiler.org)
// taco "a(i) = B(i,j) * c(j)" -f=B:ds

// Modified to remove references to `taco_tensor_t` by passing everything as func args
// Removed 0 initialization of a

int compute(double* restrict a_vals,
	    int num_of_rows,
	    int* restrict pos,
	    int* restrict crd,
	    double* restrict B_vals,
	    double* restrict c_vals) {

  for (int i = 0; i < num_of_rows; i++) {
    double tja_val = 0.0;
    for (int jB = pos[i]; jB < pos[(i + 1)]; jB++) {
      int j = crd[jB];
      tja_val += B_vals[jB] * c_vals[j];
    }
    a_vals[i] = tja_val;
  }
  return 0;
}
